version: "3"

services:
  php:
    image: "php:7.4-fpm"
    ports:
      - 9000:9000
    volumes:
      - ./data:/usr/local/apache2/htdocs:rw
    networks:
      - dokuwiki
  httpd:
    image: "httpd"
    ports:
      - 80:80
    volumes:
      - ./data:/usr/local/apache2/htdocs:rw
      - ./conf/httpd:/usr/local/apache2/conf/
    networks:
      - dokuwiki

networks:
  dokuwiki:
    driver: bridge
